---
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/setup-go@v2
      - name: Add Go bin directory to path
        run: echo "::add-path::$(go env GOPATH)/bin"
      - name: Install golint
        run: go get -u golang.org/x/lint/golint
      - uses: pre-commit/action@v2.0.0
  test:
    strategy:
      matrix:
        go-version:
          - 1.13.x
          - 1.14.x
          - 1.15.x
          - 1.16.x
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: test
        run: go test ./...
